version: "3"
services:
  rabbitmq-management:
    build: .
    container_name: "rabbitmq"
    ports:
      - 1883:1883
      - 5672:5672
      - 15672:15672
    networks:
      - net
    volumes:
      - ./conf.d:/etc/rabbitmq/conf.d/:ro
      - data:/var/lib/rabbitmq/
      - log:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - net
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"

  mongo-gui:
    container_name: "mongo-gui"
    image: ugleiton/mongo-gui
    restart: always
    ports:
      - "4321:4321"
    networks:
      - net
    environment:
      MONGO_URL: "mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/"

networks:
  net:
    driver: bridge

volumes:
  data:
  log:
