version: "3"
services:
  rabbitmq-management:
    build: .
    container_name: "rabbitmq"
    ports:
      - 1883:1883
      - 5672:5672
      - 15672:15672
    networks:
      - net
    volumes:
      - ./conf.d:/etc/rabbitmq/conf.d/:ro
      - data:/var/lib/rabbitmq/
      - log:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"

networks:
  net:
    driver: bridge

volumes:
  data:
  log:
